### ISSUE TITLE
Provide beta images

### ISSUE THREAD

**Issue by mzabaluev** [rust-lang-nursery/docker-rust#14]
It would be nice to have an official repository of up-to-date Rust beta images, to complete the rustup-like trifecta for automated CI runs and the like.

**Comment by sfackler** [comment]
Seems reasonable to me!

**Comment by TimDiekmann** [comment]
I did some tests for all three toolchains, fully automated:

Three jobs:
- `env: TOOLCHAIN=stable`
- `env: TOOLCHAIN=beta`
- `env: TOOLCHAIN=nightly`

First of all, it pulls the current image:
```
docker pull $REPOSITORY/$IMAGE_NAME:$TOOLCHAIN || true
```
then the current version is determined:
```
RUSTC_PULLED=$(docker run $REPOSITORY/$IMAGE_NAME:$TOOLCHAIN rustc --version || true)
```
Now the new image is generated:
```
- docker build --rm -t$REPOSITORY/$IMAGE_NAME --build-arg TOOLCHAIN=$TOOLCHAIN .
- RUSTC_GENERATED=$(docker run $REPOSITORY/$IMAGE_NAME rustc --version)
```
The deploy process is locked behind checking the versions to avoid unnecessary deploying:
```
deploy:
  provider: script
  script:
    - docker push $REPOSITORY/$IMAGE_NAME
  on:
    branch: master
    condition: $RUSTC_PULLED != $RUSTC_GENERATED
```
before deploying, the tags are generated:
```
- docker tag $REPOSITORY/$IMAGE_NAME $REPOSITORY/$IMAGE_NAME:$TOOLCHAIN
- if [[ $TOOLCHAIN = beta || $TOOLCHAIN = nightly ]]; then
    docker tag $REPOSITORY/$IMAGE_NAME $REPOSITORY/$IMAGE_NAME:$TOOLCHAIN;
    docker rmi $REPOSITORY/$IMAGE_NAME;
  fi
```
